min_flows = 1
max_flows = 32
port_start = 3000
duration = 20 # in seconds, for throughput benchmark
omit = 3 # in seconds, for throughput benchmark
iterations = 5 # achieve steady state, for rr benchmark
