apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: client
          image: cilium/netperf
          imagePullPolicy: IfNotPresent
          command: ["sleep"]
          args: ["infinity"]
          ports:
            - containerPort: 12865
              protocol: TCP
            - containerPort: 12865
              protocol: UDP
      nodeSelector:
        bench-role: client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: server
          image: cilium/netperf
          imagePullPolicy: IfNotPresent
          command: ["netserver"]
          args: ["-D"]
          ports:
            - containerPort: 12865
              protocol: TCP
            - containerPort: 12865
              protocol: UDP
      nodeSelector:
        bench-role: server
